/********************************************************************
* SyncCheckDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SyncCheckDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSyncCheckDict();
extern void G__cpp_setup_inheritanceSyncCheckDict();
extern void G__cpp_setup_typetableSyncCheckDict();
extern void G__cpp_setup_memvarSyncCheckDict();
extern void G__cpp_setup_globalSyncCheckDict();
extern void G__cpp_setup_memfuncSyncCheckDict();
extern void G__cpp_setup_funcSyncCheckDict();
extern void G__set_cpp_environmentSyncCheckDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SyncCheck.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SyncCheckDictLN_TObject;
extern G__linked_taginfo G__SyncCheckDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SyncCheckDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SyncCheckDictLN_TList;
extern G__linked_taginfo G__SyncCheckDictLN_TTimer;
extern G__linked_taginfo G__SyncCheckDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SyncCheckDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SyncCheckDictLN_TQObjSender;
extern G__linked_taginfo G__SyncCheckDictLN_TGWindow;
extern G__linked_taginfo G__SyncCheckDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SyncCheckDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SyncCheckDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SyncCheckDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SyncCheckDictLN_TGMainFrame;
extern G__linked_taginfo G__SyncCheckDictLN_TGStatusBar;
extern G__linked_taginfo G__SyncCheckDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SyncCheckDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SyncCheckDictLN_TH1F;
extern G__linked_taginfo G__SyncCheckDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SyncCheckDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SyncCheckDictLN_TH2F;
extern G__linked_taginfo G__SyncCheckDictLN_TGCheckButton;
extern G__linked_taginfo G__SyncCheckDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__SyncCheckDictLN_MyMainFrame;

/* STUB derived class for protected member access */
